<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FiddlerClassic.Bridge/FiddlerClassic.Bridge.csproj" />
    <ProjectReference Include="../../src/FiddlerClassic.Protocol/FiddlerClassic.Protocol.csproj" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
